"""sync user auth fields

Revision ID: db97712e0ae2
Revises: 2bee3a3a57de
Create Date: 2026-01-27 19:11:47.303618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db97712e0ae2'
down_revision: Union[str, Sequence[str], None] = '2bee3a3a57de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PATIENT', 'DOCTOR', 'ADMIN', name='user_role_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('PATIENT', 'DOCTOR', 'ADMIN', name='user_role_enum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
